# Generated by Django 4.2.7 on 2023-11-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
