# Generated by Django 4.2.7 on 2023-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_content_alter_blog_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
