# Generated by Django 4.2.7 on 2023-11-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_sub_title_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='message',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
